### ISSUE TITLE
Generating tokens is not convenient

### ISSUE THREAD

**Issue by nfroidure** [senx/warp10-docker#35]
Just installed the docker image and I wanted to create a token right inside my config files for local docker dev env but the fact that
```
docker exec -u warp10 sencrop-warp10 sh -c 'warp10-standalone.sh worf test 31536000000'
```
returns several lines
```
default options loaded from file:/opt/warp10/etc/.conf-standalone.conf.worf
{"read":{"token":"***","tokenIdent":"****","ttl":31536000000,"application":"test","applications":["test"],"owners":["***"],"producer":"f****","producers":[]},"write":{"token":"****","ttl":31536000000,"application":"test","owner":"*****","producer":"*****"}}
```
is not nice. I think that the `default options loaded from file:/opt/warp10/etc/.conf-standalone.conf.worf` text should not appear to easily load the JSON or maybe be outputted in stderr.

FYI, here is what I had to do do parse the JSON data:
```js
const WARP10 = JSON.parse(
  execSync(
    "docker exec sencrop-warp10 sh -c 'warp10-standalone.sh worf sencrop 31536000000'"
  )
    .toString()
    .split(/\r?\n/g)[1]
);
```

The fact that tokens has to be generated is not convenient too for a quick start. I like how the MySQL docker image exports the MySQL PWD on an environment variable, maybe that something similar can be done here behing an env var or an option flag.
See: https://hub.docker.com/_/mysql/

And how I can use it in my config scripts:
```js
const MYSQL_PWD = execSync(
  "docker exec sencrop-mysql sh -c 'echo $MYSQL_ROOT_PASSWORD'"
)
  .toString()
  .trim();
```

Hope it helps

**Comment by steven-gueguen** [comment]
Tokengen is now the preferred mode
