### ISSUE TITLE
Enabling Token secret for using Warp10 Docker Image

### ISSUE THREAD

**Issue by jorgevillaverde-sitewhere** [senx/warp10-docker#57]
Hi there,

We are in the process of integrating Warp10 to SiteWhere 2 and we need to enable `token.secret` in other to use `TOKENGEN` Extension of Warp Script.

We found that overriding https://github.com/senx/warp10-platform/blob/master/etc/conf.templates/distributed/70--extensions.conf.template#L55 did the trick, but we need to create a custom image for that.

Is there another way of achieving this behaviour without having to create a custom image?

Thanks

**Comment by steven-gueguen** [comment]
Hi,

There are several ways to do this:

- Using extra configuration file:
```
docker run -v /custom/99-custom.conf:/config.extra/99-custom.conf warp10io/warp10:tag
```
- Using environment variables but your secret is not so secret:
```bash
docker run -e token.secret=mysecret warp10io/warp10:tag
 ```
- Using environment file:
 ```bash
docker run --env-file=./myconf.env warp10io/warp10:tag
 ```
